# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

workflows:
   build:
      jobs:
         - build:
            context: 
               - personal_gh_releases

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.16
    environment:
      PACKAGE_PATH: "github.com/danesparza/daydash-service"
      DASH_TEST_ROOT: "/home/circleci/system.db"

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Setup Environment Variables
          command: echo 'export DEBIAN_PACKAGE_NAME="daydash-service-1.1.${CIRCLE_BUILD_NUM}"' >> $BASH_ENV 
      - run:
         name: Get compiler tool
         command: go get github.com/mitchellh/gox

      - run:
         name: Get release tool
         command: go get github.com/tcnksm/ghr
      - run:
         name: Get utilities
         command: go get github.com/danesparza/tokenreplace
      - run:
         name: Run tests
         command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports

      - run:
         name: Create binaries for all platforms
         command: mkdir -p /tmp/binaries; gox -osarch="linux/amd64 darwin/amd64" -ldflags "-X $PACKAGE_PATH/version.BuildNumber=$CIRCLE_BUILD_NUM -X $PACKAGE_PATH/version.CommitID=$CIRCLE_SHA1 -X '$PACKAGE_PATH/version.Prerelease=${EMPTY_STRING}' -X $PACKAGE_PATH/telemetry.NRLicense=${NR_DASHBOARD_LIC}" -output "/tmp/binaries/${CIRCLE_PROJECT_REPONAME}_{{.OS}}_{{.Arch}}" $PACKAGE_PATH/...
      
      - run:
         name: Setup the debian package
         command: mkdir -p "/tmp/packagestage"; cp -r /home/circleci/repo/dist "/tmp/packagestage/${DEBIAN_PACKAGE_NAME}"; chmod 755 "/tmp/packagestage/${DEBIAN_PACKAGE_NAME}/DEBIAN/postinst"; chmod 755 "/tmp/packagestage/${DEBIAN_PACKAGE_NAME}/DEBIAN/prerm"; tokenreplace -file "/tmp/packagestage/${DEBIAN_PACKAGE_NAME}/DEBIAN/control" -token="{build}" -replacement="${CIRCLE_BUILD_NUM}"; 
      - run:
         name: Create the debian package
         command: mkdir -p "/tmp/packagestage/${DEBIAN_PACKAGE_NAME}/usr/bin"; cp "/tmp/binaries/daydash-service_linux_amd64" "/tmp/packagestage/${DEBIAN_PACKAGE_NAME}/usr/bin/daydash-service"; cd /tmp/packagestage; dpkg -b "${DEBIAN_PACKAGE_NAME}"; mv *.deb "/tmp/binaries";  
         
      - run: 
         name: Push the release to Github
         command: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME v1.1.$CIRCLE_BUILD_NUM /tmp/binaries/ || true
